env:
  global:
    - CC_TEST_REPORTER_ID=257b65f48adeea04fea1fef4e4b4f4441be43fd983be4402c029fce6f4e9a277
language: ruby
rvm:
  - 2.0.0-p648
  - 2.1.10
  - 2.2.6
  - 2.3.4
  - 2.4.3
  - 2.5.1
sudo: false
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
